_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 5
                - 12
                - 53
                - 54
                - 55
            "2":
                - 5
                - 12
                - 53
                - 54
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
                - 62
            "4": 3.12.8
            "5": 0.18.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
data_file:
    value: \\10.159.50.7\LabCommon\Ken\data\Opioid_cFos\result\unbiased_adjusted_brain_heatmap
elastic_net_frac:
    value: 1
initialization:
    value: nnsvd
mask_key:
    value: 0
mask_size:
    value: 10
max_num_iters:
    value: 25
mean_func:
    value: softplus
num_coord_ascent_iters:
    value: 1
num_factors:
    value: "10"
num_mask_per_mouse:
    value: 3
sparsity_penalty:
    value: 9.999999747378752e-05
